---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/9/30 17:12
---

--region ------------- 通用回调绑定 -------------
--[[
    使用说明：通过添加一个回调，抓住新生成的绑定ID，传递到c#端抓住。当c#端触发回调时响应绑定ID，从而达到触发lua端的回调。
    注意：为了避免内存泄露，只要添加，就必须有移除(除了Once,因为已经自动处理)
--]]
local CSCallLua = {}
_G.CSCallLua = CSCallLua
CSCallLua.AllLuaCall = {}
CSCallLua.AllLuaCallType = {}
local LuaCallID = 0


---获取新的回调绑定ID
---@return number
CSCallLua.GetNewLuaCallId = function()
    LuaCallID = LuaCallID + 1
    if LuaCallID >= 2147483647 then
        LuaCallID = 1
    end
    --已绑定ID重新要一个
    if CSCallLua.AllLuaCallType[LuaCallID] ~= nil then
        return CSCallLua.GetNewLuaCallId()
    end
    return LuaCallID
end
---添加一个可以让c#回调的方法
---@param callback function 回调
---@param isOnce boolean 是否一次性
---@return number 绑定ID
CSCallLua.AddLuaCall = function(callback, isOnce)
    if isOnce == nil then
        isOnce = true
    end
    local callID = CSCallLua.GetNewLuaCallId()
    CSCallLua.AllLuaCallType[callID] = isOnce
    CSCallLua.AllLuaCall[callID] = callback
    return callID
end

---移除绑定回调
---@param callID function 绑定ID
function CSCallLua.RemoveLuaCall(callID)
    CSCallLua.AllLuaCall[callID] = nil
    CSCallLua.AllLuaCallType[callID] = nil
end


---绑定到CS侧的方法
CSCallLua.Call = function(callID, ...)
    local isOnce = CSCallLua.AllLuaCallType[callID]
    local fun = CSCallLua.AllLuaCall[callID]
    if fun ~= nil then
        fun(...)
    end
    if isOnce == true then
        CSCallLua.RemoveLuaCall(callID)
    end
end
--绑定到C#侧
CS.CSCallLuaHelp.CallLua = CSCallLua.Call
CS.CSCallLuaHelp.CallLuaInt = CSCallLua.Call
CS.CSCallLuaHelp.CallLuaStr = CSCallLua.Call
CS.CSCallLuaHelp.CallLuaFloat = CSCallLua.Call
CS.CSCallLuaHelp.CallLuaGameObject = CSCallLua.Call
CS.CSCallLuaHelp.CallLuaAssetResRef = CSCallLua.Call
CS.CSCallLuaHelp.CallLuaTransInt = CSCallLua.Call

return CSCallLua