---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/10/13 13:50
---
local Language = require("Language")
local Type_Key = require("Type_Key")

---@class LanguageUtil 语言包工具
local LanguageUtil = {}
_G.LanguageUtil = LanguageUtil
---@type Language
_G.Language = Languagen



---取得本地化字段
---@param targetCfg Language 配置表
---@param item Language_Item key
---@return string 本地化字段Value
function LanguageUtil:GetLocalizeValue(targetCfg, item, ...)
    local key
    if type(item) == Type_Key.Tab then
        key = item.Key
    elseif type(item) == Type_Key.Str then
        key = item
    end

    ---@type Language_Item
    local value
    local args = table.pack(...)

    value = targetCfg[key]
    if value then
        if args.n > 0 then
            value = string.format(value.CN, table.unpack(args))
        else
            value = value.CN
        end
    end
    if not value then
        value = key
    end
    if value == nil then
        return nil
    end
    return value
end


---取得程序本地化字段
---@param item Language_Item
---@return string 本地化字段Value
function LanguageUtil:GetValue(item, ...)
    return LanguageUtil:GetLocalizeValue(Language, item, ...)
end

--endregion
return LanguageUtil