---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/10/17 17:04
---

local UIBase = require("UIBase")
local UIManager = require("UIManager")
local tableSort = table.sort
local tableInsert = table.insert
local tableRemovebyvalue = table.removebyvalue

---@class MaskView : UIBase 窗口
---@field private go_table MaskView_GoTable GoTable
---@field private ParentCls UIBase 父窗口类
local MaskView = Class("MaskView", UIBase)

function MaskView:__init()
    self.super:__init()

    self.MaskUIArray = {}

end

---窗口显示(子类重写自定义每个参数)
---@protected
---@param uiInstance UIBase 第一个窗口实例
function MaskView:OnCreate(...)
    self:SetActive(true)
    local uiInstance = self.UIParam[1]
    self:AddMaskUI(uiInstance)
    UIManager:GetInstance().MaskView = self
end


---@param uiInstance UIBase 添加一个ui实例
function MaskView:AddMaskUI(uiInstance)
    tableInsert(self.MaskUIArray,uiInstance)
    self:RefreshOrder()
    self.go_table.obj_UIMask:SetActive(true)
end

---@param uiInstance UIBase 移除一个ui实例
function MaskView:RemoveMaskUI(uiInstance)
    tableRemovebyvalue(self.MaskUIArray,uiInstance)
    if table.count(self.MaskUIArray) > 0 then
        self:RefreshOrder()
        self.go_table.obj_UIMask:SetActive(true)
    else
        self.go_table.obj_UIMask:SetActive(false)
    end
end

function MaskView:RefreshOrder(parent,order)
    tableSort(self.MaskUIArray,function(a, b)
        ---@type UIBase
        local InstA = a
        ---@type UIBase
        local InstB = b
        if InstA.UILayer == InstB.UILayer then
            return InstA.SortOrder > InstB.SortOrder
        else
            return InstA.UILayer > InstB.UILayer
        end
    end)
    ---@type UIBase
    local topUIInst = self.MaskUIArray[1]
    self.transform:SetParent(topUIInst.ParentNode, false)
    local canvas = self.gameObject:GetComponent(typeof(Canvas))
    if IsNil(canvas) then
        Log.LogFatal("%s 自行添加Canvas组件", self.UIName)
    end

    -- 设置它的canvas深度
    canvas.overrideSorting = true
    --canvas.additionalShaderChannels = TexCoord1
    canvas.sortingOrder = topUIInst.SortOrder - 5
end

return MaskView