---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/9/30 11:20
---

---@class EventID
---@field
local EventID = Class("EventID")

local ID_LuaEvent_Start = 1000000000

---获取EventID
---@return number EventID
function EventID:CreateEventID()
    ID_LuaEvent_Start = ID_LuaEvent_Start + 1
    return ID_LuaEvent_Start
end

function EventID:IsLuaEvent(id)
    return (id >= ID_LuaEvent_Start)
end


--region ------------- 网络连接 -------------
---Lua端开始对远程主机连接
EventID.ConnectStart = EventID:CreateEventID()
---Lua端连接成功
EventID.ConnectOK = EventID:CreateEventID()
---Lua端连接失败
EventID.ConnectFail = EventID:CreateEventID()
---Lua端连接关闭
EventID.ConnectClose = EventID:CreateEventID()
---Lua端重连成功
EventID.ReconnectComplete = EventID:CreateEventID()
---Lua端发出队列消息
EventID.SendMsg = EventID:CreateEventID()
---Lua端发出消息
EventID.SendParallelMsg = EventID:CreateEventID()
---Lua端接收队列消息
EventID.ReceiveMsg = EventID:CreateEventID()
---Lua端接收消息
EventID.ReceiveParallelMsg = EventID:CreateEventID()
---Lua端接收数据出错
EventID.ReceiveMsgError = EventID:CreateEventID()
--endregion ----------- 网络连接 end -----------


--region ------------- UI -------------
---界面打开完成(纯逻辑打开时抛和OnUIClosed配对)
EventID.OnViewOpened = EventID:CreateEventID()
---界面完全打开完成(资源加载完成OnShow之后抛)
EventID.OnViewCompletedOpened = EventID:CreateEventID()
---界面逻辑关闭完成
EventID.OnViewClosed = EventID:CreateEventID()
---界面激活显示(Note:第一次打开窗口不会触发)
EventID.OnViewShow = EventID:CreateEventID()
---界面隐藏显示
EventID.OnViewHide = EventID:CreateEventID()
--endregion ----------- UI end -----------

_G.EventID = EventID
---@type EventID
return EventID