---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/10/9 19:02
---
local ListItemBase = require("ListItemBase")
local UIComBase = require("UIComBase")
local GameEvent = require("GameEvent")
local Log = require("Log")
local DeviceDataInst = require("DeviceData"):GetInstance()
local DeviceData = require("DeviceData")
local UIInst = require("UIManager"):GetInstance()
local GameDataInst = require("GameData"):GetInstance()
local EventInst = require("EventManager"):GetInstance()

---@class DeviceUnlockItem : UIComBase 组件
---@field private go_table DeviceUnlockItem_GoTable GoTable
---@field private ParentCls UIComBase 父窗口类
local DeviceUnlockItem = Class("DeviceUnlockItem", ListItemBase)

---添加Events监听事件
function DeviceUnlockItem:Awake()
    self:AddEvent(GameEvent.UpGradeFurnitureEvent)
    self:AddEvent(GameEvent.FurnitureOnTheWayOverEvent)
end
--- 窗口显示[protected]
---@param ... any @窗口传参
function DeviceUnlockItem:OnCreate()
    -- self.isFisrt = true
end
---@public
---@param UnlockData furniture_level_Item
---@param Level number
function DeviceUnlockItem:InitUnlockItemData(UnlockData, index, ...)
    if index ~= nil then
        -- Log.Debug("DeviceUnlockItem init:" .. UnlockData.id .. ",i:" .. index)
    end

    self.FurnitureId = UnlockData.id--当前家具id
    self.FieldId = UnlockData.furniture_id--当前栏位id
    self.HouseId = DeviceDataInst:GetHouseId(self.FurnitureId)--当前房间id
    self.myTerm = GameDataInst.Popular--我的人气

    self.FurnitureData = UnlockData

    local isUsing = DeviceDataInst:IsUsingFurniture(self.HouseId, self.FieldId, self.FurnitureId)--当前家具是否正在使用

    if (isUsing) then
        --正在使用
        self.furnitureStatus = DeviceData.furnitureStatus.isUseing
    else
        self.furnitureStatus = DeviceData.furnitureStatus.Lock
        local isUnLock = DeviceDataInst:FurnitureIsUnlock(self.HouseId, self.FieldId, self.FurnitureId)--当前家具是否解锁

        if (isUnLock) then
            --已解锁
            self.furnitureStatus = DeviceData.furnitureStatus.NotUseing
        else
            --未解锁
            local could = DeviceDataInst:FurnitureCouldUnlock(self.FurnitureId)

            if (could) then
                --达到解锁条件
                local isBought = DeviceDataInst:FurnitureUnlockButWait(self.FurnitureId)

                if (isBought) then
                    --运输中 已购买
                    local isOnTheWay = DeviceDataInst:FurnitureIsOnTheWay(self.FurnitureId)
                    if (isOnTheWay) then
                        self.furnitureStatus = DeviceData.furnitureStatus.OnTheway
                    else
                        --运输完成 等待点击解锁
                        self.furnitureStatus = DeviceData.furnitureStatus.UnlockFinsh
                    end
                else
                    --未购买
                    self.furnitureStatus = DeviceData.furnitureStatus.Notbought
                end


            else
                self.furnitureStatus = DeviceData.furnitureStatus.Lock
            end

        end
    end

    self.spritName = UnlockData.icon

    self:InitStatusShow(nil)


end
function DeviceUnlockItem:InitStatusShow(status)
    if (status ~= nil) then
        self.furnitureStatus = status
    end

    self.go_table.img_notSelect.gameObject:SetActive(self.furnitureStatus ~= DeviceData.furnitureStatus.isUseing)

    self.go_table.simg_newImg.gameObject:SetActive(false)

    self.go_table.obj_state_2:SetActive(false)
    self.go_table.obj_state_1:SetActive(false)
    self.go_table.obj_state_3:SetActive(false)
    self.go_table.obj_state_4:SetActive(false)
    self.go_table.obj_state_5:SetActive(false)

    local alpha = 1
    if (self.furnitureStatus == DeviceData.furnitureStatus.Lock) then
        --未解锁

        self.go_table.obj_state_3:SetActive(true)
        alpha = 0.5
    elseif self.furnitureStatus == DeviceData.furnitureStatus.Notbought then
        --未购买
        self.go_table.obj_state_2:SetActive(true)
        --local isNew = false
        --[[        if (self.isFisrt) then
                    self.isFisrt = false
                    --第一次进入界面
                    isNew = DeviceDataInst:IsNewFurniture(self.HouseId, self.FieldId, self.FurnitureId)
                end]]
        local isNew = DeviceDataInst:IsNewFurniture(self.HouseId, self.FieldId, self.FurnitureId)
        self.go_table.simg_newImg.gameObject:SetActive(isNew)
        -- fieldData.NewUnlockFurnitureIds[furnitureId] = furnitureId

        alpha = 0.5
    elseif self.furnitureStatus == DeviceData.furnitureStatus.NotUseing then
        --已购买 未使用

    elseif self.furnitureStatus == DeviceData.furnitureStatus.OnTheway then
        --正在运输
        self.go_table.obj_state_4:SetActive(true)
        self.go_table.stmp_OntheWayStr.text = LanguageUtil:GetValue("Commom_ontransi")

    elseif self.furnitureStatus == DeviceData.furnitureStatus.UnlockFinsh then
        --完成运输 等待解锁
        self.go_table.obj_state_5:SetActive(true)
        --self.go_table.simg_newImg.gameObject:SetActive(true)
        self.go_table.stmp_UnlockIsFinsh.text = LanguageUtil:GetValue("Common_transportend")

    else
        --已购买 正在使用
        self.go_table.obj_state_1:SetActive(true)
        self.go_table.stmp_state.text = LanguageUtil:GetValue("Common_button_useing")
    end

    local normalTab = self.FurnitureData.cost_normal
    local normalCostType = normalTab[1]
    local normalCostNum = normalTab[2]

    local iconNameFast = GameDataInst:GetCostImageName(normalCostType)
    self.go_table.img_IconImage:LoadSprite(GameDefine.eResPath.AtlasMain .. iconNameFast, false, 1)
    self.go_table.stmp_num.text = normalCostNum

    self.go_table.simg_icon_item:LoadSprite(GameDefine.eResPath.AtlasFurniture .. self.spritName, false, alpha)

end

---事件处理
---@private
---@param id EventID 事件ID
function DeviceUnlockItem:EventHandle(id, ...)
    local tab = { ... }
    local furnitureId = tab[1]

    if (id == GameEvent.UpGradeFurnitureEvent) then
        --正在运输中
        --[[     if (self.FurnitureId == furnitureId) then
                 self:InitUnlockItemData(self.FurnitureData)
             end]]
    elseif id == GameEvent.FurnitureOnTheWayOverEvent then
        --运输已完成
        if (self.FurnitureId == furnitureId) then
            self:InitUnlockItemData(self.FurnitureData)
        end
    end
end

---可用
---@protected
function DeviceUnlockItem:OnEnable()
end

---不可用
---@protected
function DeviceUnlockItem:OnDisable()
end

---点击Button回调
---@param btn UnityEngine.UI.Button 按钮
function DeviceUnlockItem:OnClickBtn(btn)

    if (btn == self.go_table.btn_bgbtn) then
        if (self.furnitureStatus == DeviceData.furnitureStatus.UnlockFinsh) then
            --点击运输完成
            EventInst:Broadcast(GameEvent.RoomFurnitureLookAt, self.FurnitureId)
            self.OwnerUI:Close()
        else

            if (self.furnitureStatus == DeviceData.furnitureStatus.Notbought) then
                DeviceDataInst:SetOldFurniture(self.FurnitureData.id)
                self:InitStatusShow()
            end
            UIInst:OpenUIDefine(UIDefine.DeviceDescView, nil, self.FurnitureData, self.furnitureStatus)
        end

    end
end

---点击Toggle回调
---@protected
---@param toggle UnityEngine.UI.Toggle Toggle
---@param isOn boolean 是否选中
function DeviceUnlockItem:OnClickToggle(toggle, isOn)
end

---数据清理
---@protected
function DeviceUnlockItem:OnDestroy()
    --DeviceUnlockItem.ParentCls.OnDestroy(self)
end

return DeviceUnlockItem