---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/10/13 18:23
---
local UIBase = require("UIBase")
local LanguageUtil = LanguageUtil

---@class PopBase:UIBase @弹出窗口基类
---@field IsPop boolean 是否弹窗
---@field ClickSpaceClose boolean 点击空白关闭，默认打开
---@field HasOpenTween boolean 是否有打开动画
---@field OnOpenTweenFinished fun() 打开动画完成时
---@field HasCloseTween boolean 是否有关闭动画
---@field OnCloseTweenFinished fun() 关闭动画完成时
local PopBase = Class("PopBase",UIBase)

---添加Events监听事件
function PopBase:OnBaseAwake()
    self.ClickSpaceClose = false
    self.HasOpenTween = true
    self.HasCloseTween = true
    self.IsPop = true

    self:Awake()
end
---模拟Unity Component的 Awake
---@protected
function PopBase:Awake()
end

--- 窗口显示[protected]
---@param ... any @窗口传参
function PopBase:OnCreate()
end

---事件处理
---@private
---@param id EventID 事件ID
function PopBase:EventHandle(id, ...)
end

---可用
---@protected
function PopBase:OnEnable()
end

---不可用
---@protected
function PopBase:OnDisable()
end
---设置标题
---@param titleStr string 标题
function PopBase:SetTitle(titleStr)
    if self.go_table.stmp_title then
        self.go_table.stmp_title.text = titleStr
    end
end

---设置标题Lang
---@param titleLang Language_Item 标题
---@param ... any 参数
function PopBase:SetTitleLang(titleLang,...)
    if self.go_table.stmp_title then
        self.go_table.stmp_title.Text = LanguageUtil:GetValue(titleLang,...)
    end
end

---重写UIBase的点击Button回调，
---@private
function PopBase:OnBaseClickBtn(btn)
    if btn == self.go_table.btn_anyClose and self.ClickSpaceClose then
        self:Close()
    end
    self:OnClickBtn(btn)
end

---点击Button回调
---@param btn UnityEngine.UI.Button 按钮
function PopBase:OnClickBtn(btn)
end

---点击Toggle回调
---@protected
---@param toggle UnityEngine.UI.Toggle Toggle
---@param isOn boolean 是否选中
function PopBase:OnClickToggle(toggle, isOn)

end

---点击tmp Link回调
---@protected
---@param tmp SEngine.UI.STMP
---@param linkId string
function PopBase:OnClickTmp(tmp, linkId)
end

---显示弹窗打开动画
---@override
---@param callback fun() 动画完毕
function PopBase:ShowOpenTween(callback)
    if self.HasOpenTween and  self.transform then
        ---@type UnityEngine.Transform
        local trans = self.transform
        trans:SetLocalScaleXYZ(0.5)
        --trans.localScale.x = 0.5
        --trans.localScale.y = 0.5
        trans:DOScale(1.1, 0.1):OnComplete(function()
            trans:DOScale(1, 0.03):OnComplete(function()
                if callback then callback() end
            end)
        end)
    else
    end
end

---显示弹窗关闭动画
---@override
---@param callback fun() 动画完毕
function PopBase:ShowCloseTween(callback)
    if callback then callback() end
end

---设置content的高度
---@param height number
function PopBase:SetContentHeught(height)
    local adaptiveheight = self.go_table.transform:Find("Root").gameObject:GetComponent(typeof(CS.AdaptiveHeight))
    if adaptiveheight ~= nil then
        adaptiveheight:Start()
        adaptiveheight:SetHeight(height)
    end
end

---数据清理
---@protected
function PopBase:OnDestroy()
    --MainView.ParentCls.OnDestroy(self)
end


return PopBase