---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/10/14 19:28
---
local EventID = require("EventID")
---@class PopEvent
local PopEvent = {}

---打开动画事件ID
PopEvent.OnOpenTweenFinish = EventID:CreateEventID()

return PopEvent