---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/10/9 19:02
---

local SceneViewBase = require("SceneViewBase")
local GameEvent = require("GameEvent")
local Log = require("Log")
local SceneManager = require("SceneManager")
local SceneInst = require("SceneManager"):GetInstance()
local MachineInst = require("EggMachine"):GetInstance()
local GameDataInst = require("GameData"):GetInstance()
local EventInst = require("EventManager"):GetInstance()
local EggMachine = require("EggMachine")
local GameDefine = GameDefine
local HotelDataInst = require("HotelData"):GetInstance()
local TimerInst = require("TimerManager"):GetInstance()
local AvatarManager = require("AvatarManager")
local AvatarView = require("AvatarView")
local AvatarEvent = require("AvatarEvent")
local ResLoadManager = require("ResLoadManager")
---出生点信息
---@class AvatarBornNodeInfo
---@field Index number 位置id
---@field Empty boolean 是否为空
---@field BornNode UnityEngine.GameObject 出生位置

---出生点信息
---@class ParticleData
---@field Particle Coffee.UIExtensions.UIParticle 粒子特效
---@field CountTime number 计时时间
---@field StartTime number 开始时间
---@field ShowTime number 持续多久
---@field isPaused boolean 是否暂停

---@class HotelSceneView : SceneViewBase 旅店室外
---@field private go_table HotelSceneView_GoTable GoTable
---@field private ParentCls UIBase 父窗口类
---@field private AvatarBornNodeMap table<number,AvatarBornNodeInfo> 出生点map
local HotelSceneView = Class("HotelSceneView", SceneViewBase)

---@class HotelSceneView.HotelTask 旅店任务
HotelSceneView.HotelTask = {
    ChangeJar = 1, --小费罐
    Restaurant = 2, --餐厅解锁
    Stairs = 3, --修楼梯
    Room201 = 4, --解锁房间201
    Hall = 5, --修复大厅
    Room202 = 6, -- 解锁房间202
    Rooftop = 7, --楼顶
    Notice = 8, --告示栏
    SecondFloor = 9, --二楼地板
    FunctionRoom = 10, --功能房
}

---添加Events监听事件
function HotelSceneView:Awake()
    self:AddEvent(EggMachine.ClickOnce)
    self:AddEvent(EggMachine.NewBuffStart)
    self:AddEvent(EggMachine.RoundComplete)
    self:AddEvent(GameEvent.FinshHotelTaskEvent)
    self:AddEvent(AvatarEvent.ClearAvatarView)
    self:AddEvent(AvatarEvent.EnterRoom)
    self:AddEvent(AvatarEvent.ExitRoom)
    self:AddEvent(GameEvent.BtnMachine)
end

--- 窗口显示[protected]
---@param ... any @窗口传参
function HotelSceneView:OnCreate()
    self:ResetSceneSize(Vector2.New(1024, 1024), Vector3.New(1, 1.8, 1.1), Vector2.New(0, 150))
    self:InitSceneView()

    self.RoomId = SceneManager.eRoomId.Hotel
    self.MaxJDValue = 2.15
    self:InitAvatarBornInfo()

    self:InitMachineSpine()
    self:InitAvatars()
    --self.go_table.obj_chuizi.transform.localPosition = self.go_table.obj_changeJar_lock.transform.localPosition
    ---帧刷新
    self.OrderTimer = TimerInst:GetTimerStartImme(2, self.OnOrderTimer, self, false, true);
end

---事件处理
---@private
---@param id EventID 事件ID
function HotelSceneView:EventHandle(id, ...)
    if id == EggMachine.ClickOnce then
    elseif id == EggMachine.RoundComplete then
        ---一轮消耗一点体力
        local costTl
        if (MachineInst.PlayState == EggMachine.ePlayState.Normal) then
            costTl = 1
        else
            costTl = Config.gashapon_machine_sp[MachineInst.PlayState].energy_cost
        end

        GameDataInst:ChangePlayerProp(GameDefine.ePlayerProp.Energy, -costTl)
        self:OnRoundComplete(...)
    elseif id == GameEvent.FinshHotelTaskEvent then
        --完成旅店任务
        self:OnFinishHotelTask(...)
    elseif id == AvatarEvent.ClearAvatarView then
        self:OnClearAvatarView(...)
    elseif id == AvatarEvent.EnterRoom then
        self:OnAvatarEnterRoom(...)
    elseif id == AvatarEvent.ExitRoom then
        self:OnAvatarExitRoom(...)
    elseif id == EggMachine.NewBuffStart then
        --扭蛋机获取到了最新BUFF
        self:InitMachineSpine()
    elseif id == GameEvent.BtnMachine then
        self:SafePlayAnim("click1", false, function()
            self.MachineSpine:PlayAnim("idle", true)
        end)
        MachineInst:ClickMachine()
        --设置进度
        if (MachineInst.PlayState == EggMachine.ePlayState.Enough) then
            MachineInst.ClickNum = 1
        end
        local value = MachineInst:GetJDValue() * self.MaxJDValue
        self.MachineSpine:SetBonePropValue("JD", "Y", value)
        EventInst:Broadcast(GameEvent.EggMachineProgress, MachineInst:GetJDValue())
    end
end

function HotelSceneView:SafePlayAnim(name, loop, complete)
    if self.MachineSpine then
        self.MachineSpine:PlayAnim(name, loop, complete)
    end
end

---可用
---@protected
function HotelSceneView:OnEnable()
end

---不可用
---@protected
function HotelSceneView:OnDisable()
end

---点击Button回调
---@param btn UnityEngine.UI.Button 按钮
function HotelSceneView:OnClickBtn(btn)
    if btn == self.go_table.sbtn_Lounge then
        SceneInst:ChangeToRoom(SceneManager.eRoomId.Lounge)
    elseif btn == self.go_table.sbtn_machine then
        --[[
        self:SafePlayAnim("click1", false, function()
            self.MachineSpine:PlayAnim("idle", true)
        end)
        MachineInst:RoundComplete()
        --设置进度
        if (MachineInst.PlayState == EggMachine.ePlayState.Enough) then
            MachineInst.ClickNum = 1
        end
        local value = MachineInst:GetJDValue() * self.MaxJDValue
        self.MachineSpine:SetBonePropValue("JD", "Y", value)
        EventInst:Broadcast(GameEvent.EggMachineProgress, MachineInst:GetJDValue())
        ]]
    end
end

---点击Toggle回调
---@protected
---@param toggle UnityEngine.UI.Toggle Toggle
---@param isOn boolean 是否选中
function HotelSceneView:OnClickToggle(toggle, isOn)
end

--region --------------------------- 初始化----------------------------
---初始化怪物出生点
---
function HotelSceneView:InitAvatarBornInfo()
    self.AvatarBornNodeMap = {}
    for i = 1, 8 do
        local node = self.go_table["obj_avatar_pos_" .. i]
        if node ~= nil then
            ---@type AvatarBornNodeInfo
            local info = {
                Index = i,
                Empty = true,
                BornNode = node
            }
            self.AvatarBornNodeMap[i] = info
        end
    end
end

function HotelSceneView:InitMachineSpine()
    local clickNum = HotelDataInst.EggMachine.ClickNum --存储的点击次数
    MachineInst.ClickNum = clickNum
    MachineInst:GetRoundClickNum()--获取总次数

    local state = MachineInst.PlayState
    ---@type SEngine.UI.UISpine
    self.MachineSpine = self.go_table.obj_machine:GetComponent(typeof(CS.SEngine.UI.UISpine))
    self.MachineSpine:PlayAnim("idle", true)
    --设置进度
    if (state == EggMachine.ePlayState.Enough) then
        MachineInst.ClickNum = 1
    end

    local value = MachineInst:GetJDValue() * self.MaxJDValue
    self.MachineSpine:SetBonePropValue("JD", "Y", value)
    EventInst:Broadcast(GameEvent.EggMachineProgress, MachineInst:GetJDValue())
    ---处理BUFF显示
    if (state == EggMachine.ePlayState.Enough) then
        local path = GameDefine.eResPath.EffectPath .. "Fx_Prefab/Fx_Gashapon_lightning"

        ---加载预制
        ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
            if go ~= nil then
                go.transform:SetParent(self.go_table.obj_machineBuff.transform)
                go:ResetPRS()
                go.transform.localPosition = Vector3.New(0, -41, 0)
            end
        end)
    elseif (state == EggMachine.ePlayState.Double) then
        local path = "UI/Hotel/Prefabs/bat1"
        ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
            if go ~= nil then
                go.transform:SetParent(self.go_table.obj_machineBuff.transform)
                go:ResetPRS()
                go.transform:SetLocalScaleXYZ(0.16)
                go.transform.localPosition = Vector3.New(0, 38, 0)
                ---@type SEngine.UI.UISpine
                local batSpine = go.transform:GetComponent(typeof(CS.SEngine.UI.UISpine))
                if (MachineInst.isShow) then
                    batSpine:PlayAnim("idle", true)
                else
                    batSpine:PlayAnim("fly", false, function()
                        batSpine:PlayAnim("idle", true)
                    end)
                end
                MachineInst.isShow = true
            end
        end)
    elseif (state == EggMachine.ePlayState.Spirit) then
        local path = "UI/Hotel/Prefabs/jingling"
        ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
            if go ~= nil then
                go.transform:SetParent(self.go_table.obj_machineBuff.transform)
                go:ResetPRS()
                go.transform:SetLocalScaleXYZ(1)
                go.transform.localPosition = Vector3.New(0, 0, 0)

                if (MachineInst.isShow) then
                    self:SafePlayAnim("click1", true, function()

                    end)
                else
                    self:SafePlayAnim("click1", true, function()

                    end)
                end
                MachineInst.isShow = true
                --[[        local hide = go.transform:GetComponent(typeof(CS.HideNodeSpine))
                        if hide ~= nil then
                            hide:HidChildSpine()
                        end]]
            end
        end)

    elseif (state == EggMachine.ePlayState.Intrusion) then
        local path = GameDefine.eResPath.EffectPath .. "Fx_Prefab/Fx_Bug"
        ---加载预制
        ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
            if go ~= nil then
                go.transform:SetParent(self.go_table.obj_machineBuff.transform)
                go:ResetPRS()
                go.transform:SetLocalScaleXYZ(0.35)
                go.transform.localPosition = Vector3.New(0, 11, 0)
            end
        end)
    end
end

---初始化角色
function HotelSceneView:InitAvatars()
    ---管理所有avtarView
    local avatarMachines = AvatarManager:GetInstance():GetRoomAvatarMachines(self.RoomId)
    if avatarMachines ~= nil then
        for i = 1, #avatarMachines do
            local avatarGo, shadowGo = self:CloneAvatarNode(self.go_table.obj_scene)
            ---@type AvatarView
            local avatarView = self:GetOrAddComponent(avatarGo, require("AvatarView"), 1.5, true, shadowGo)
            local machine = avatarMachines[i]
            machine:SetView(avatarView)
        end
    end
end

function HotelSceneView:OnAvatarEnterRoom(roomId, avatarId)
    if roomId == self.RoomId then
        local avatarGo, shadowGo = self:CloneAvatarNode(self.go_table.obj_scene)
        ---@type AvatarView
        local avatarView = self:GetOrAddComponent(avatarGo, require("AvatarView"), 1.5, true, shadowGo)
        local machine = AvatarManager:GetInstance():GetAvatarMachineById(avatarId)
        machine:SetView(avatarView)
    end
end

function HotelSceneView:OnAvatarExitRoom(roomId, avatarId)
    if roomId == self.RoomId then
        self:OnClearAvatarView(avatarId)
    end
end
---清除avatarview
---@param avatarId number
function HotelSceneView:OnClearAvatarView(avatarId)
    local machine = AvatarManager:GetInstance():GetAvatarMachineById(avatarId)
    local view = machine.View
    self:RemoveComponentInstance(view)
    machine:SetView(nil)
end

function HotelSceneView:ClearAllAvatarView()
    local avatarMachines = AvatarManager:GetInstance():GetRoomAvatarMachines(self.RoomId)
    if avatarMachines ~= nil then
        for i = 1, #avatarMachines do
            avatarMachines[i]:SetView(nil)
        end
    end
end

--endregion --------------------------- 初始化----------------------------

--region --------------- 扭蛋机精灵 --------------------------------

---一轮结束出蛋
---@param playState EggMachine.ePlayState
---@param roundEggs table<number,EggMachine.EggInfo>
function HotelSceneView:OnRoundComplete(playState, roundEggs)
    self:SafePlayAnim("click2", false, function()
        self.MachineSpine:PlayAnim("idle", true)
    end)

    for i, v in pairs(roundEggs) do
        local nodeInfo = self:GetEmptyBornNodeInfo(v)
        if nodeInfo ~= nil then
            ---被占用
            nodeInfo.Empty = false
            ---转换到局部坐标
            local startPos = self.go_table.obj_machine.transform:ConvertLocalPositionToParent(CSUIModel.UICamera, self.go_table.obj_scene.transform)
            local endPos = nodeInfo.BornNode.transform.localPosition
            local controlPos = Vector3.New((startPos.x + endPos.x) / 2, startPos.y + 20, 0)
            local ballGo = self:CloneBallNode(self.go_table.obj_scene, startPos, v.EggId)
            ballGo.transform:DoBezier2(startPos, controlPos, endPos, 0.4):OnComplete(function()
                ballGo:DestroyGameObj()
                self:ShowAvatarAppearEffect(nodeInfo, v)

                if (MachineInst.PlayState ~= EggMachine.ePlayState.Normal and i == #roundEggs) then
                    MachineInst.BuffUse = MachineInst.BuffUse + 1
                    if (MachineInst.BuffUse >= Config.gashapon_machine_sp[MachineInst.PlayState].use_number) then
                        --使用次数用尽
                        MachineInst.BuffUse = 0
                        MachineInst.PlayState = EggMachine.ePlayState.Normal
                        MachineInst.ClickNum = 0
                        MachineInst.isShow = false
                        MachineInst:SaveEggMachineData()

                        for j = 1, self.go_table.obj_machineBuff.transform.childCount do
                            self.go_table.obj_machineBuff.transform:ClearChildren(j - 1)
                        end
                        self:InitMachineSpine()
                        HotelDataInst.EggMachineTime = 0 --从新计算倒计时BUFF
                    end
                elseif MachineInst.PlayState == EggMachine.ePlayState.Normal then
                    MachineInst.ClickNum = 0
                    MachineInst:SaveEggMachineData()
                    MachineInst:CheckPlayState()

                end
            end)  :SetEase(CS.DG.Tweening.Ease.OutSine)
        end
    end


end

---显示扭蛋机生成精灵特效
---@param bornInfo AvatarBornNodeInfo 出生点info
---@param eggInfo EggMachine.EggInfo 扭蛋机info
function HotelSceneView:ShowAvatarAppearEffect(bornInfo, eggInfo)
    local fxPath = GameDefine.eResPath.EffectPath .. "Fx_Prefab/Fx_Smoke_Appear"
    self:LoadParticle(fxPath, bornInfo.BornNode, function(uiParticle)
        uiParticle:Play()
        ---延时
        uiParticle.gameObject.transform:DOScale(1, 0.2):OnComplete(function()
            ---创建avatar
            local avatarGo, shadowGo = self:CloneAvatarNode(self.go_table.obj_scene)
            ---@type AvatarView
            local avatarView = self:GetOrAddComponent(avatarGo, require("AvatarView"), 1.5, true, shadowGo)
            ---@type AvatarStateMachine
            local machine = AvatarManager:GetInstance():CreateAvatar(bornInfo, eggInfo)
            machine:SetView(avatarView)
            bornInfo.Empty = true

        end)
        TimerInst:GetTimerStart(1, function()
            uiParticle.gameObject:DestroyGameObj()
        end, self, true)
    end)
end

---获取空的出生点
---@param egg EggMachine.EggInfo
---@return AvatarBornNodeInfo
function HotelSceneView:GetEmptyBornNodeInfo(egg)
    local emptyBornNodes = {}
    for i, v in pairs(self.AvatarBornNodeMap) do
        if v.Empty == true then
            table.insert(emptyBornNodes, v)
        end
    end
    if #emptyBornNodes > 0 then
        return emptyBornNodes[Mathf.Random(1, #emptyBornNodes)]
    end
    return nil
end

---@param pNode UnityEngine.GameObject
---@return UnityEngine.GameObject
function HotelSceneView:CloneAvatarNode(pNode)
    ---@type UnityEngine.GameObject
    local avatarGo = CS.UnityEngine.Object.Instantiate(self.go_table.obj_avatar, pNode.transform)
    avatarGo.transform.localPosition = Vector3.zero
    avatarGo.transform.gameObject:SetActive(true)
    --avatarGo.transform:SetLocalScaleXYZ(1.5)

    local shadowGo = CS.UnityEngine.Object.Instantiate(self.go_table.img_shadow.gameObject, self.go_table.obj_shadows.transform)
    shadowGo.transform.gameObject:SetActive(true)
    ---spine
    return avatarGo, shadowGo
end

function HotelSceneView:CloneBallNode(pNode, pos, eggId)
    ---@type UnityEngine.GameObject
    local ballGo = CS.UnityEngine.Object.Instantiate(self.go_table.obj_ball, pNode.transform)
    ---@type SEngine.UI.UISpine
    local spine = ballGo.transform:GetComponent(typeof(CS.SEngine.UI.UISpine))
    local skin = Config.gashapon_machine_config[eggId].egg_skin
    spine:SetSkin(skin)
    ballGo.transform.localPosition = pos
    ballGo.transform.gameObject:SetActive(true)
    ballGo.transform:SetLocalScaleXYZ(0.2)

    ---spine
    return ballGo
end

---精灵排序
function HotelSceneView:OnOrderTimer()
    ---@type UnityEngine.RectTransform[]
    local sceneChildrenTrans = {}
    for i = 1, self.go_table.obj_scene.transform.childCount do
        local child = self.go_table.obj_scene.transform:GetChild(i - 1)
        table.insert(sceneChildrenTrans, child)
    end
    table.sort(sceneChildrenTrans, function(a, b)
        return a.localPosition.y > b.localPosition.y
    end)
    for i = 1, #sceneChildrenTrans do
        sceneChildrenTrans[i]:SetSiblingIndex(i - 1)
    end
end
--endregion --------------- 扭蛋机精灵 --------------------------------

--region ---------------------建造修复--------------------------
function HotelSceneView:InitSceneView()
    --所有任务
    for i = 1, 10 do
        if i == HotelSceneView.HotelTask.ChangeJar then
            self:ShowChangeJar(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.Restaurant then
            self:ShowRestaurant(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.Stairs then
            self:ShowStairs(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.Room201 then
            self:ShowRoom201(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.Hall then
            self:ShowHall(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.Room202 then
            self:ShowRoom202(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.Rooftop then
            self:ShowRooftop(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.Notice then
            self:ShowNotice(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.SecondFloor then
            self:ShowSecondFloor(HotelDataInst:IsTaskActionFinish(i))
        elseif i == HotelSceneView.HotelTask.FunctionRoom then
            self:ShowFunctionRoom(HotelDataInst:IsTaskActionFinish(i))
        end
    end
end

function HotelSceneView:OnFinishHotelTask(taskId)
    local type = Config.hotlebuild[taskId].param
    if type == HotelSceneView.HotelTask.ChangeJar then
        self:CameraMoveTo(self.go_table.obj_changeJar_open.transform.localPosition, 0.5, function()

            local x = self.go_table.obj_changeJar_open.transform.localPosition.x
            local y = self.go_table.obj_changeJar_open.transform.localPosition.y
            local pos = Vector2.New(x, y)

            self:ChuiziBuild("idle", pos, false, function()
                self:ShowChangeJar(true)
                self.go_table.simg_jarImg:ShowUIShiny(1.5)
            end)
        end)
    elseif type == HotelSceneView.HotelTask.Restaurant then
        self:CameraMoveTo(self.go_table.obj_restaurant_open.transform.localPosition, 0.5, function()
            local x = self.go_table.obj_restaurant_open.transform.localPosition.x
            local y = self.go_table.obj_restaurant_open.transform.localPosition.y
            local pos = Vector2.New(x, y + 10)
            self:ChuiziBuild("idle2", pos, false, function()
                self:ShowRestaurant(true)
                self.go_table.simg_reastImg:ShowUIShiny(1.5)
            end)
        end)
    elseif type == HotelSceneView.HotelTask.Stairs then
        self:CameraMoveTo(self.go_table.obj_stairs_open.transform.localPosition, 0.5, function()
            local pos = self.go_table.obj_stairs_open.transform.localPosition
            self:ChuiziBuild("idle2", pos, false, function()
                self:ShowStairs(true)
                self.go_table.simg_stairsimg:ShowUIShiny(1.5)
            end)
        end)
    elseif type == HotelSceneView.HotelTask.Room201 then
        self:CameraMoveTo(self.go_table.obj_room201_break.transform.localPosition, 0.5, function()

            local x = self.go_table.obj_room201_break.transform.localPosition.x
            local y = self.go_table.obj_room201_break.transform.localPosition.y
            local pos = Vector2.New(x, y + 10)
            self:ChuiziBuild("idle2", pos, false, function()
                self:ShowRoom201(true)
                self.go_table.simg_room201img:ShowUIShiny(1.5)
            end)
        end)
    elseif type == HotelSceneView.HotelTask.Hall then
        self:CameraMoveTo(self.go_table.obj_hall_ditan.transform.localPosition, 0.5, function()
            ---固定点位出现
            self.saobaPosArray = {}
            for i = 1, self.go_table.obj_saobaPos.transform.childCount do
                local childNode = self.go_table.obj_saobaPos.transform:GetChild(i - 1)
                if (childNode ~= nil) then
                    table.insert(self.saobaPosArray, childNode.transform.localPosition)
                end
            end

            local path = "UI/Hotel/Prefabs/saoba"
            ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
                if go ~= nil then
                    go.transform:SetParent(self.go_table.obj_saobaNodes.transform)
                    go:ResetPRS()
                    go.transform:SetLocalScaleXYZ(0.05)

                    self.saobaPreFab = go
                    local index = 1
                    self:DoSaoBaFourAction(index)
                end
            end)


        end)
    elseif type == HotelSceneView.HotelTask.Room202 then
        self:CameraMoveTo(self.go_table.obj_room202_break.transform.localPosition, 0.5, function()

            local x = self.go_table.obj_room202_break.transform.localPosition.x
            local y = self.go_table.obj_room202_break.transform.localPosition.y
            local pos = Vector2.New(x, y + 10)
            self:ChuiziBuild("idle2", pos, false, function()
                self:ShowRoom202(true)
                self.go_table.simg_room202img:ShowUIShiny(1.5)
            end)
        end)
    elseif type == HotelSceneView.HotelTask.Rooftop then
        self:CameraMoveTo(self.go_table.obj_rooftop_room.transform.localPosition, 0.5, function()


            self.saobaPosMoveArray = {}

            for i = 2, self.go_table.obj_saobaTopPos.transform.childCount do
                local childNode = self.go_table.obj_saobaTopPos.transform:GetChild(i - 1)
                if (childNode ~= nil) then
                    table.insert(self.saobaPosMoveArray, childNode.transform.localPosition)
                end
            end
            local x = self.go_table.obj_sbTopStartPos.transform.localPosition.x
            local y = self.go_table.obj_sbTopStartPos.transform.localPosition.y
            local pos = Vector2.New(x, y)
            local path = "UI/Hotel/Prefabs/saoba"
            ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
                if go ~= nil then
                    go.transform:SetParent(self.go_table.obj_saobaNodes.transform)
                    go:ResetPRS()
                    go.transform:SetLocalScaleXYZ(0.05)
                    go.transform.localPosition = pos
                    ---从一个点到一个点 移动出现
                    self:DoSaoBaActionMove(go, pos, function()
                        self:ShowRooftop(true)
                        self.go_table.simg_rooftoproomImg:ShowUIShiny(1.5)
                    end)
                end
            end)


        end)
    elseif type == HotelSceneView.HotelTask.Notice then
        self:CameraMoveTo(self.go_table.obj_notice_open.transform.localPosition, 0.5, function()

            local x = self.go_table.obj_notice_lock.transform.localPosition.x
            local y = self.go_table.obj_notice_lock.transform.localPosition.y
            local pos = Vector2.New(x, y + 10)
            self:ChuiziBuild("idle2", pos, false, function()
                self:ShowNotice(true)
                self.go_table.simg_noticeimg:ShowUIShiny(1.5)
            end)
        end)

    elseif type == HotelSceneView.HotelTask.SecondFloor then
        self:CameraMoveTo(self.go_table.obj_room202_break.transform.localPosition, 0.5, function()

            self.saobaPosMoveArray = {}

            for i = 2, self.go_table.obj_saobaFloor2Pos.transform.childCount do
                local childNode = self.go_table.obj_saobaFloor2Pos.transform:GetChild(i - 1)
                if (childNode ~= nil) then
                    table.insert(self.saobaPosMoveArray, childNode.transform.localPosition)
                end
            end
            local x = self.go_table.obj_sbMoveStartPos.transform.localPosition.x
            local y = self.go_table.obj_sbMoveStartPos.transform.localPosition.y
            local pos = Vector2.New(x, y + 10)
            local path = "UI/Hotel/Prefabs/saoba"
            ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
                if go ~= nil then
                    go.transform:SetParent(self.go_table.obj_saobaNodes.transform)
                    go:ResetPRS()
                    go.transform:SetLocalScaleXYZ(0.05)
                    go.transform.localPosition = pos

                    ---从一个点到一个点 移动出现
                    self:DoSaoBaActionMove(go, pos, function()
                        self:ShowSecondFloor(true)
                        self.go_table.obj_csmOpen:SetActive(true)
                        self.go_table.simg_csmimg:ShowUIShiny(1.5)
                        self.go_table.simg_bgimg:ShowUIShiny(1.5)
                    end)
                end
            end)


        end)

    elseif type == HotelSceneView.HotelTask.FunctionRoom then
        self:CameraMoveTo(self.go_table.obj_funcRoom.transform.localPosition, 0.5, function()

            local x = self.go_table.obj_funcRoomLock.transform.localPosition.x
            local y = self.go_table.obj_funcRoomLock.transform.localPosition.y
            local pos = Vector2.New(x, y + 10)
            self:ChuiziBuild("idle2", pos, false, function()
                self:ShowFunctionRoom(true)
                self.go_table.simg_funcRoomimg:ShowUIShiny(1.5)
            end)

        end)
    end
end

function HotelSceneView:ChuiziBuild(name, pos, loop, func)
    local path = "UI/Hotel/Prefabs/chuizi"
    ResLoadManager:GetInstance():LoadObj(path, ResTypeEnum.ePrefab, true, function(go)
        if go ~= nil then
            go.transform:SetParent(self.go_table.obj_czNodes.transform)
            go:ResetPRS()
            go.transform:SetLocalScaleXYZ(0.05)
            go.transform.localPosition = pos
            ---@type SEngine.UI.UISpine
            local batSpine = go.transform:GetComponent(typeof(CS.SEngine.UI.UISpine))
            if (name == "idle2") then
                batSpine:PlayAnim(name, loop, function()
                    batSpine:PlayAnim(name, loop, function()
                        batSpine:PlayAnim(name, loop, function()
                            batSpine:PlayAnim(name, loop, function()
                                go.gameObject:DestroyGameObj()
                                func()
                            end)
                        end)
                    end)
                end)

            else
                batSpine:PlayAnim(name, loop, function()
                    go.gameObject:DestroyGameObj()
                    func()
                end)
            end

        end
    end)
end

---一个点到另外一个点移动
function HotelSceneView:DoSaoBaActionMove(node, pos, func)
    if (table.count(self.saobaPosMoveArray) <= 0 or self.saobaPosMoveArray[1] == nil) then
        self.saobaPosMoveArray = {}
        func()
        node.gameObject:DestroyGameObj()
        return
    end
    local batSpine = node.transform:GetComponent(typeof(CS.SEngine.UI.UISpine))
    batSpine:PlayAnim("idle", true)
    local endPos = self.saobaPosMoveArray[1]
    node.transform:DOLocalMove(endPos, 2):OnComplete(function()
        table.removebyvalue(self.saobaPosMoveArray, endPos)
        self:DoSaoBaActionMove(node, pos, func)
    end)
end

---解锁大厅 四个位置播放扫把
function HotelSceneView:DoSaoBaFourAction(index)
    local i = index
    if self.saobaCountNum == nil then
        self.saobaCountNum = 0
    end
    if (i > self.go_table.obj_saobaPos.transform.childCount) then
        self.saobaPosArray = {}
        self.saobaPreFab.transform:DestroyGameObj()
        self:ShowHall(true)
        self.go_table.simg_ditanimg:ShowUIShiny(1.5)
        return
    end
    local pos = self.go_table.obj_saobaPos.transform:GetChild(i - 1).localPosition
    self.saobaPreFab.transform.localPosition = pos
    ---@type SEngine.UI.UISpine
    local batSpine = self.saobaPreFab.transform:GetComponent(typeof(CS.SEngine.UI.UISpine))

    batSpine:PlayAnim("idle", false, function()
        self.saobaCountNum = self.saobaCountNum + 1
        if (self.saobaCountNum >= 2) then
            i = i + 1
            self.saobaCountNum = 0
            self:DoSaoBaFourAction(i)
        else
            self:DoSaoBaFourAction(i)
        end
    end)
end

---显示小费罐
function HotelSceneView:ShowChangeJar(isShow)
    self.go_table.obj_changeJar_lock.gameObject:SetActive(not isShow)
    self.go_table.obj_changeJar_open.gameObject:SetActive(isShow)
end
---显示餐厅
function HotelSceneView:ShowRestaurant(isShow)
    self.go_table.obj_restaurant_lock.gameObject:SetActive(not isShow)
    self.go_table.obj_restaurant_open.gameObject:SetActive(isShow)
end
---显示梯子
function HotelSceneView:ShowStairs(isShow)
    self.go_table.obj_stairs_lock.gameObject:SetActive(not isShow)
    self.go_table.obj_stairs_open.gameObject:SetActive(isShow)
end
---显示房间201
function HotelSceneView:ShowRoom201(isShow)
    self.go_table.obj_room201_break.gameObject:SetActive(not isShow)
end
---显示大厅
function HotelSceneView:ShowHall(isShow)
    self.go_table.obj_hall_break.gameObject:SetActive(not isShow)
    self.go_table.obj_hall_ditan.gameObject:SetActive(isShow)
end
---显示房间202
function HotelSceneView:ShowRoom202(isShow)
    self.go_table.obj_room202_break.gameObject:SetActive(not isShow)
end
---显示房顶
function HotelSceneView:ShowRooftop(isShow)
    self.go_table.obj_rooftop_break.gameObject:SetActive(not isShow)
    self.go_table.obj_rooftop_room.gameObject:SetActive(isShow)
end
---显示公共蓝
function HotelSceneView:ShowNotice(isShow)
    self.go_table.obj_notice_lock.gameObject:SetActive(not isShow)
    self.go_table.obj_notice_open.gameObject:SetActive(isShow)
end

--二楼地板
function HotelSceneView:ShowSecondFloor(isShow)
    self.go_table.obj_secendFloorBreak.gameObject:SetActive(not isShow)
end
--功能房
function HotelSceneView:ShowFunctionRoom(isShow)
    self.go_table.obj_funcRoomLock.gameObject:SetActive(not isShow)
    self.go_table.obj_funcRoom.gameObject:SetActive(isShow)
end

--endregion ---------------------建造修复--------------------------


---数据清理
---@protected
function HotelSceneView:OnDestroy()
    --HotelSceneView.ParentCls.OnDestroy(self)
    TimerInst:StopAndClearTimer(self.ParticleTimer)
    TimerInst:StopAndClearTimer(self.OrderTimer)
    MachineInst:ResetClick()
    self:ClearAllAvatarView()
end

return HotelSceneView