---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/10/8 11:43
---
local Log = require("Log")

local CS = _G.CS

local CSUIGoTable = typeof(CS.UIGoTable)

---获取go_table组件
---@param node UnityEngine.GameObject 窗口预制体
---@param onClickBtn fun(btn: UnityEngine.UI.Button) 点击回调
---@param onClickToggle fun(toggle:UnityEngine.UI.Toggle, isOn:boolean) 点击回调
---@param onClickTmp fun(stmp:SEngine.UI.STMP)点击超链接
function _G.GetAutoGoTable(node, onClickBtn, onClickToggle, onClickTmp)
    assert(type(node) == "userdata", "类型不正确" .. type(node))
    local comp = node:GetComponent(CSUIGoTable)
    if _G.IsNil(comp) then
        Log.LogFatal("%s 未挂载 UIGoTable 组件", node.name)
    else
        local tbl = comp:CreateLuaGoTable()
        if (onClickBtn ~= nil) then
            tbl["_onClickBtn"] = onClickBtn
        end
        if (onClickToggle ~= nil) then
            tbl["_onClickToggle"] = onClickToggle
        end
        if (onClickTmp ~= nil) then
            tbl["_onClickTmp"] = onClickTmp
        end
        return tbl
    end
    return {}
end

---获取go_table组件(没有则返回nil)
---@param node UnityEngine.GameObject 窗口预制体
---@param onClickBtn fun(btn: UnityEngine.UI.Button) 点击回调
---@param onClickToggle fun(toggle:UnityEngine.UI.Toggle, isOn:boolean) 点击回调
---@param onClickTmp fun(stmp:SEngine.UI.STMP)点击超链接
function _G.GetAutoGoTableOrNil(node, onClickBtn, onClickToggle, onClickTmp)
    assert(type(node) == "userdata", "类型不正确" .. type(node))
    local comp = node:GetComponent(CSUIGoTable)
    if not _G.IsNil(comp) then
        local tbl = comp:CreateLuaGoTable()
        if (onClickBtn ~= nil) then
            tbl["_onClickBtn"] = onClickBtn
        end
        if (onClickToggle ~= nil) then
            tbl["_onClickToggle"] = onClickToggle
        end
        if (onClickTmp ~= nil) then
            tbl["_onClickTmp"] = onClickTmp
        end
        return tbl
    end
    return nil
end