---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/9/29 13:51
---

---@class AppSetting 系统设置
---@field UsedAssetBundle boolean 是否使用AssetBundle
---@field UsedLuaAssetBundle boolean 是否使用UsedLuaAssetBundle
local AppSetting = {}

AppSetting.LogLevel = CS.System.Convert.ToInt32(CS.Launcher.Instance.LogLevel)

AppSetting.UsedAssetBundle = CS.Launcher.Instance.UsedAssetBundle

AppSetting.UsedLuaAssetBundle = CS.Launcher.Instance.UsedLuaAssetBundle

---@type AppSetting
_G.AppSetting = AppSetting
---@type AppSetting
return AppSetting
