---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/9/29 13:41
---

_G.realRequire = _G.require

local lazyRequire = require("lazyRequire")

local AppSetting = require "AppSetting"

--region -------------Common-------------

require "TableUtil"
require "LuaUtil"
require "StringUtil"
require "Log"
require "Class"
require "DataClass"
require "ConstClass"
require "Singleton"

--endregion

--region -------------UnityEngine-------------
require "InitUnityEngine"
--require "CSCallLua"
--endregion

--region -------------Config-------------
--require "ConfigManager"
--endregion

--region -------------Updater-------------
--require "Timer"
--require "TimerManager"
--require "TimeUtil"
--endregion


--region -------------Event-------------
--require "EventManager"
--require "EventID"
--endregion


--region --------------UI-----------------
--require "UIManager"
--endregion

--region --------------Module-----------------
require "GameDefine"
--endregion

---懒加载
_G.require = lazyRequire

--重新require一个lua文件，替代系统文件。
function reimport(name)
    local package = package
    if package.loaded[name] then
        package.loaded[name] = nil
        package.preload[name] = nil
    end
    return realRequire(name)
end
_G.CS.XLuaManager.LuaReimport .LuaReimport = function(filePath)
    _G.reimport(filePath)
end