---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/9/29 13:41
---

_G.realRequire = _G.require

local lazyRequire = require("lazyRequire")

local AppSetting = require "AppSetting"

--region -------------Common-------------

require "TableUtil"
require "LuaUtil"
require "StringUtil"
require "UITool"
require "Log"
require "Class"
require "DataClass"
require "ConstClass"
require "Singleton"
require "list"
require "event"

--endregion

--region -------------UnityEngine-------------
require "InitUnityEngine"
require "CSCallLua"
--endregion

--region -------------Updater-------------
require "Timer"
require "TimerManager"
require "TimeUtil"
--endregion


--region -------------Event-------------
require "Event"
require "EventManager"
require "EventID"
--endregion


--region -------------Resource-------------
require "ResTypeEnum"
require "ResLoadManager"
--endregion

--region -------------Config-------------
require "serpent"
require "ConfigDataDefine"
require "ConfigManager"
require "LanguageUtil"
require "PlayerPrefsUtil"
--endregion


--region --------------UI-----------------
require "UILayerEnum"
require "UIBase"
require "UIComBase"
require "UIManager"
--endregion

--region --------------Module-----------------
require "GameDefine"
--endregion

--region --------------Utils-----------------
require "LoopListViewHelper"
--endregion
---懒加载
_G.require = lazyRequire

--重新require一个lua文件，替代系统文件。
function reimport(name)
    local package = package
    if package.loaded[name] then
        package.loaded[name] = nil
        package.preload[name] = nil
    end
    return realRequire(name)
end
_G.CS.XLuaManager.LuaReimport = function(filePath)
    _G.reimport(filePath)
end