---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/9/29 13:41
---
require("Init")
local Log = require("Log")
local EventManager = require("EventManager")
local GameEvent = require("GameEvent")
local UIManager = require("UIManager")
local UIDefine = require("UIDefine")

local GameData = require("GameData")
local HotelData = require("HotelData")
local DeviceData = require("DeviceData")


---@class LuaLauncher 游戏的主入口，一般由C#端调用
local LuaLauncher = {}

_G.LuaLauncher = LuaLauncher

-- 主入口函数。
function LuaLauncher:Start()
     print("<color=red><size=18>Lua LuaLauncher: Start</size></color>")
     --初始化一些必要的管理器
     self:StartupLuaLogic()
     local cs = _G.CS;
     EventManager:GetInstance():AddListener(GameEvent.TestEvent1,self.OnTestEvent,self)
     EventManager:GetInstance():Broadcast(GameEvent.TestEvent1,"xxx")
end

function LuaLauncher:StartupLuaLogic()
end

function LuaLauncher:OnTestEvent(arg)
     Log.Debug(arg)
     UIManager:GetInstance():OpenUIDefine(UIDefine.LoginView)
end

return LuaLauncher