---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/9/29 13:41
---

--require("Init")

---@class LuaLauncher 游戏的主入口，一般由C#端调用
local LuaLauncher = {}
_G.LuaLauncher = LuaLauncher

-- 主入口函数。
function LuaLauncher:Start()
     print("<color=red><size=18>Lua LuaLauncher: Start</size></color>")
    --self:StartLuaLogic()
end