---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/11/17 15:45
---


---@class BaseState 状态机状态
---@field Name string 名字
---@field Machine StateMachine 状态机引用
local BaseState = Class("BaseState")


---@private
function BaseState:__init(name)
    self.Name = name
end

---状态机更新
---@override
function BaseState:Update()

end
---进入状态
---@override
function BaseState:Enter()

end

---退出状态
---@override
function BaseState:Exit()

end

return BaseState