---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/11/21 18:59
---
local EventID = require("EventID")
---@class AvatarEvent
local AvatarEvent = {}

---清除场景avatar
AvatarEvent.ClearAvatarView = EventID:CreateEventID()
---休息室排队更新
AvatarEvent.LoungeWaitUpdate = EventID:CreateEventID()
---家具使用排队更新
AvatarEvent.FurnitureWaitUpdate = EventID:CreateEventID()
---进入房间
AvatarEvent.EnterRoom = EventID:CreateEventID()
---离开房间
AvatarEvent.ExitRoom = EventID:CreateEventID()

return AvatarEvent