---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/11/17 16:54
---
local AvatarState = require("AvatarState")
local EventManager = require("EventManager")
local AvatarEvent = require("AvatarEvent")
local AvatarManager = require("AvatarManager")
local MapManager = require("MapManager")
local AvatarStateMachine = require("AvatarStateMachine")

------@class HotelMoveState:AvatarState 旅店移动
---@field Machine AvatarStateMachine
---@field Speed number 移动速度
local HotelMoveState = Class("HotelMoveState",AvatarState)


function HotelMoveState:__init()
    self.Speed = 30
end

---进入状态
---@override
function HotelMoveState:Enter()
    self:AddEvent()

    self.Machine:SetInfoAnim("walk",true)
    --设置移动目标
    if self.Machine.Info.GotoPos > 0 then
        local gotoPos = MapManager:GetInstance().Positions[self.Machine.Info.GotoPos]
        local moveTargetPos = gotoPos[#gotoPos]
        if moveTargetPos ~= nil then
            self.Machine:MoveToTarget(moveTargetPos,self.Speed)
        end
    end
end

function HotelMoveState:AddEvent()
end

function HotelMoveState:RemoveEvent()
end
---退出状态
---@override
function HotelMoveState:Exit()
    self:RemoveEvent()
end


---状态机更新
---@override
function HotelMoveState:Update()
    if self.Machine.IsArriveTarget then
        self.Machine.IsArriveTarget = nil
        -----到了
        if self.Machine.Info.GotoPos == MapManager.ePosition.OutPoint then
            ---出去
            self.Machine:ClearAvatar()
        elseif self.Machine.Info.GotoPos == MapManager.ePosition.LoungeRoomWait then
            local loungeWaiter = AvatarManager:GetInstance():GetStateMachines(AvatarStateMachine.eStateName.LoungeWait)
            if #loungeWaiter >= #MapManager:GetInstance().Positions[MapManager.ePosition.LoungeRoomWait] then
                ---标记去过了，重新找目标
                self.Machine:SaveEnterRoom(1001)
                self.Machine:ChangeState(AvatarStateMachine.eStateName.HotelStand)
            else
                ---去等候排队
                self.Machine.Info.QueueIndex = #loungeWaiter + 1
                self.Machine:ChangeState(AvatarStateMachine.eStateName.LoungeWait)
            end
        end
    end
end
return HotelMoveState