---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/11/25 11:56
---
local MapManager = require("MapManager")
local AvatarState = require("AvatarState")
local AvatarManager = require("AvatarManager")
local AvatarStateMachine = require("AvatarStateMachine")
local ConfigManager = require("ConfigManager")
local SceneManager = require("SceneManager")
local DeviceData = require("DeviceData")

------@class LoungeMoveState:AvatarState 休息室移动
---@field Machine AvatarStateMachine
---@field QueueIndex number
local LoungeMoveState = Class("LoungeMoveState",AvatarState)

function LoungeMoveState:__init()
    self.Speed = 30
end

---进入状态
---@override
function LoungeMoveState:Enter()

    self.Machine:SetInfoAnim("walk",true)
    self.Machine:SetInfoSkin("Guest_2")

    --设置移动目标
    if self.Machine.Info.GotoPos > 0 then
        local moveTargetPos = nil
        if self.Machine.Info.GotoPos ~= MapManager.ePosition.Furniture then
            local gotoPos = MapManager:GetInstance().Positions[self.Machine.Info.GotoPos]
            moveTargetPos = gotoPos[#gotoPos]
        else

            --设备，去等待
            local furniturePoses = MapManager:GetInstance().FurnitureQueuePosDic[self.Machine.Info.UseFurnitureId]
            moveTargetPos = furniturePoses[#furniturePoses]
        end
        if moveTargetPos ~= nil then
            self.Machine:MoveToTarget(moveTargetPos,self.Speed)
        end
    end

end
---状态机更新
---@override
function LoungeMoveState:Update()
    if self.Machine.IsArriveTarget then
        self.Machine.IsArriveTarget = nil
        -----到了
        if self.Machine.Info.GotoPos == MapManager.ePosition.LoungeDoor then
            ---出去房间
            self.Machine:EnterRoom(SceneManager.eRoomId.Hotel)
            self.Machine:ChangeState(AvatarStateMachine.eStateName.HotelStand)
        elseif self.Machine.Info.GotoPos == MapManager.ePosition.Furniture then
            local furnitureId = self.Machine.Info.UseFurnitureId
            local furId = DeviceData:GetInstance():GetCurUseFurnitureData(self.Machine.Info.RoomId,furnitureId)
            if furId ~= nil then
                ---有家具去排队
                --验证排队
                local waiter = AvatarManager:GetInstance():GetFurnitureStateMachines(AvatarStateMachine.eStateName.WaitFurniture,furnitureId)
                if #waiter < MapManager:GetInstance():GetFurnitureWaitMaxCount(furnitureId) then
                    --去排队
                    self.Machine.Info.UseFurnitureId = furnitureId
                    self.Machine.Info.QueueIndex = #waiter + 1
                    self.Machine:ChangeState(AvatarStateMachine.eStateName.WaitFurniture)
                else
                    --寻找下一个目标
                    self.Machine:ChangeState(AvatarStateMachine.eStateName.LoungeStand)
                end
            else
                ---没用家具显示需求
                self.Machine.Info.UseFurnitureId = furnitureId
                self.Machine:ChangeState(AvatarStateMachine.eStateName.NeedFurniture)
            end
        end
    end

end
---退出状态
---@override
function LoungeMoveState:Exit()

end
return LoungeMoveState