---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/11/17 16:57
---
local AvatarState = require("AvatarState")
local EventManager = require("EventManager")
local AvatarEvent = require("AvatarEvent")
local AvatarManager = require("AvatarManager")
local AvatarStateMachine = require("AvatarStateMachine")
local MapManager = require("MapManager")
local SceneManager = require("SceneManager")
local ConfigManager = require("ConfigManager")

------@class LoungeWaitState:AvatarState 房间排队
---@field Machine AvatarStateMachine
---@field QueueIndex number
local LoungeWaitState = Class("LoungeWaitState",AvatarState)

function LoungeWaitState:__init()
    self.Speed = 20
end

---进入状态
---@override
function LoungeWaitState:Enter()
    self:AddEvent()
    --设置位置
    self.Machine:SetInfoAnim("idle",true)

    self.QueueIndex = self.Machine.Info.QueueIndex
    self:SetTargetAndMove(self.QueueIndex)
    self.CheckEnter = false
    ---@type furniture_Item
    local door = ConfigManager.GetConfigByField(ConfigManager.furniture,"furniture_used",{1})[1]
    self.DoorFurnitureId = door.id
end

function LoungeWaitState:SetTargetAndMove(queueIndex)
    local targetPos = MapManager:GetInstance().Positions[MapManager.ePosition.LoungeRoomWait][queueIndex]
    ---移动到pos
    if targetPos ~= nil then
        self.Machine:SetInfoAnim("walk",true)
        self.Machine:MoveToTarget(targetPos,self.Speed)
    end
end

function LoungeWaitState:AddEvent()
    EventManager:GetInstance():AddListener(AvatarEvent.LoungeWaitUpdate,self.OnLoungeWaitUpdate,self)
end

function LoungeWaitState:RemoveEvent()
    EventManager:GetInstance():RemoveListener(AvatarEvent.LoungeWaitUpdate,self.OnLoungeWaitUpdate,self)
end

function LoungeWaitState:OnLoungeWaitUpdate()
    self.QueueIndex = self.QueueIndex -1
    self.Machine.Info.QueueIndex = self.QueueIndex
    self:SetTargetAndMove(self.QueueIndex)
end
---退出状态
---@override
function LoungeWaitState:Exit()
    self.QueueIndex = nil
    self:RemoveEvent()
end


---状态机更新
---@override
function LoungeWaitState:Update()
    if self.Machine.IsArriveTarget then
        self.Machine.IsArriveTarget = nil
        self.Machine:SetInfoAnim("idle",true)
        if self.QueueIndex == 1 then
            self.CheckEnter = true
        end
    end

    if self.CheckEnter then
        --找等待使用门的人
        local doorWaiter = AvatarManager:GetInstance():GetFurnitureStateMachines(AvatarStateMachine.eStateName.WaitFurniture,self.DoorFurnitureId)
        if #doorWaiter < MapManager:GetInstance():GetFurnitureWaitMaxCount(self.DoorFurnitureId) then
            --有排队空位
            self.Machine:EnterRoom(SceneManager.eRoomId.Lounge)
            --更新排队
            self:RemoveEvent()
            EventManager:GetInstance():Broadcast(AvatarEvent.LoungeWaitUpdate)
            self.Machine.Info.UseFurnitureId = self.DoorFurnitureId
            self.Machine.Info.QueueIndex = #doorWaiter + 1
            self.Machine:ChangeState(AvatarStateMachine.eStateName.WaitFurniture)
        end
    end
end

return LoungeWaitState