---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/12/8 14:56
---
local MapManager = require("MapManager")
local AvatarState = require("AvatarState")
local AvatarManager = require("AvatarManager")
local AvatarStateMachine = require("AvatarStateMachine")
local ConfigManager = require("ConfigManager")
local SceneManager = require("SceneManager")
local EventManager = require("EventManager")
local GameEvent = require("GameEvent")

------@class NeedFurnitureState:AvatarState 需求家具状态
---@field Machine AvatarStateMachine
local NeedFurnitureState = Class("NeedFurnitureState",AvatarState)

function NeedFurnitureState:__init()
end

---进入状态
---@override
function NeedFurnitureState:Enter()
    self.FurnitureTypeId = self.Machine.Info.UseFurnitureId
    self.FurnitureConfig = ConfigManager.furniture[self.FurnitureTypeId]
    ---@type expression_bubble_Item
    self.BubbleConfig = Config.GetConfigByField(ConfigManager.expression_bubble,"bubble_type",{AvatarStateMachine.eHudType.NeedFurniture})[1]

    self.Machine:SetInfoAnim("idle",true)

    self.NeedFurnitureId = self:GetNeedFurnitureId()
    self.Machine:SetInfoBubble(self.BubbleConfig.id,self.NeedFurnitureId)
    self.StartTime = self.Machine.Time

    self:AddEvent()
end

function NeedFurnitureState:AddEvent()
    EventManager:GetInstance():AddListener(GameEvent.FurnitureOnTheWayOverEvent,self.OnFurnitureOver,self)
end
function NeedFurnitureState:RemoveEvent()
    EventManager:GetInstance():RemoveListener(GameEvent.FurnitureOnTheWayOverEvent,self.OnFurnitureOver,self)
end

function NeedFurnitureState:OnFurnitureOver(fId)
    if fId == self.NeedFurnitureId then
        ---建造完了
        self.Machine.Info.IsAngry = false
        self.Machine:SetInfoBubble(0)
        --验证排队
        local waiter = AvatarManager:GetInstance():GetFurnitureStateMachines(AvatarStateMachine.eStateName.WaitFurniture,self.FurnitureTypeId)
        if #waiter < MapManager:GetInstance():GetFurnitureWaitMaxCount(self.FurnitureTypeId) then
            --去排队
            self.Machine.Info.UseFurnitureId = self.FurnitureTypeId
            self.Machine.Info.QueueIndex = #waiter + 1
            self.Machine:ChangeState(AvatarStateMachine.eStateName.WaitFurniture)
        else
            --寻找下一个目标
            self.Machine:ChangeState(AvatarStateMachine.eStateName.LoungeStand)
        end
    end
end

function NeedFurnitureState:GetNeedFurnitureId()
    ---@type furniture_level_Item[]
    local furnitures = Config.GetConfigByField(ConfigManager.furniture_level,"furniture_id",{self.FurnitureTypeId})
    for i = 1, #furnitures do
        if furnitures[i].level == 1 then
            return furnitures[i].id
        end
    end
    return 0
end

---状态机更新
---@override
function NeedFurnitureState:Update()
    local time = self.Machine.Time
    ---1秒后move
    if time -self.StartTime > self.BubbleConfig.time then
        ---超时没建造
        self.Machine.Info.IsAngry = true
        --已经使用的id
        table.insert(self.Machine.Info.UsedFurnitureIds,self.FurnitureTypeId)
        ---从可能使用中移除
        if table.ContainsValue(self.Machine.Info.CanUseFurnitureIds,self.FurnitureTypeId) then
            table.removebyvalue(self.Machine.Info.CanUseFurnitureIds,self.FurnitureTypeId)
        end

        self.Machine:SetInfoBubble(0)
        --寻找下一个目标
        self.Machine:ChangeState(AvatarStateMachine.eStateName.LoungeStand)
    end
end


---退出状态
---@override
function NeedFurnitureState:Exit()
    self.StartTime = 0
    self:RemoveEvent()
end

return NeedFurnitureState