---@class DeviceUseTimeView_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public btn_anyClose UnityEngine.UI.Button
---@field public sbtn_cancle SEngine.UI.SButton
---@field public sbtn_confirm SEngine.UI.SButton
---@field public stmp_LockStr SEngine.UI.STMP
---@field public stmp_Message SEngine.UI.STMP
---@field public stmp_title SEngine.UI.STMP
---@field public stmp_unlockStr SEngine.UI.STMP

