---@class DeviceListItem_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public img_conditionImg SEngine.UI.SImage
---@field public img_IconImageFast SEngine.UI.SImage
---@field public list_DeviceUnlockList SuperScrollView.LoopListView2
---@field public obj_contion UnityEngine.GameObject
---@field public obj_DeviceUnlockItem UnityEngine.GameObject
---@field public sbtn_finishImme SEngine.UI.SButton
---@field public stmp_conditionText SEngine.UI.STMP
---@field public stmp_costNum SEngine.UI.STMP
---@field public stmp_deviceTitle SEngine.UI.STMP
---@field public stmp_unlock SEngine.UI.STMP

---@class DeviceListItem_DeviceUnlockItem_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public btn_bgbtn SEngine.UI.SButton
---@field public img_IconImage SEngine.UI.SImage
---@field public img_notSelect UnityEngine.UI.Image
---@field public img_select UnityEngine.UI.Image
---@field public obj_state_1 UnityEngine.GameObject
---@field public obj_state_2 UnityEngine.GameObject
---@field public obj_state_3 UnityEngine.GameObject
---@field public obj_state_4 UnityEngine.GameObject
---@field public obj_state_5 UnityEngine.GameObject
---@field public simg_icon_item SEngine.UI.SImage
---@field public simg_newImg SEngine.UI.SImage
---@field public stmp_num SEngine.UI.STMP
---@field public stmp_OntheWayStr SEngine.UI.STMP
---@field public stmp_state SEngine.UI.STMP
---@field public stmp_UnlockIsFinsh SEngine.UI.STMP

