---@class DeviceUnlockItem_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public btn_bgbtn SEngine.UI.SButton
---@field public img_IconImage SEngine.UI.SImage
---@field public img_notSelect UnityEngine.UI.Image
---@field public img_select UnityEngine.UI.Image
---@field public obj_notUseNode UnityEngine.GameObject
---@field public obj_state_1 UnityEngine.GameObject
---@field public obj_state_2 UnityEngine.GameObject
---@field public obj_state_3 UnityEngine.GameObject
---@field public obj_state_4 UnityEngine.GameObject
---@field public obj_state_5 UnityEngine.GameObject
---@field public simg_bigbg SEngine.UI.SImage
---@field public simg_icon_item SEngine.UI.SImage
---@field public simg_newImg SEngine.UI.SImage
---@field public simg_notUseItem SEngine.UI.SImage
---@field public stmp_num SEngine.UI.STMP
---@field public stmp_OntheWayStr SEngine.UI.STMP
---@field public stmp_state SEngine.UI.STMP
---@field public stmp_UnlockIsFinsh SEngine.UI.STMP

