---@class HotelViewItem_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public img_IconImage SEngine.UI.SImage
---@field public img_rewardImg SEngine.UI.SImage
---@field public obj_condition UnityEngine.GameObject
---@field public obj_extraReward UnityEngine.GameObject
---@field public obj_finger UnityEngine.GameObject
---@field public sbtn_finishImme SEngine.UI.SButton
---@field public simg_chuizi SEngine.UI.SImage
---@field public simg_conImg SEngine.UI.SImage
---@field public simg_finshimg SEngine.UI.SImage
---@field public simg_teskImg SEngine.UI.SImage
---@field public stmp_conStr SEngine.UI.STMP
---@field public stmp_costNum SEngine.UI.STMP
---@field public stmp_rewardNum SEngine.UI.STMP
---@field public stmp_taskName SEngine.UI.STMP

