---@class LoungeSceneView_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public obj_10001 UnityEngine.GameObject
---@field public obj_10002 UnityEngine.GameObject
---@field public obj_10003 UnityEngine.GameObject
---@field public obj_10004 UnityEngine.GameObject
---@field public obj_10005 UnityEngine.GameObject
---@field public obj_10006 UnityEngine.GameObject
---@field public obj_10007 UnityEngine.GameObject
---@field public obj_10008 UnityEngine.GameObject
---@field public obj_10009 UnityEngine.GameObject
---@field public obj_10010 UnityEngine.GameObject
---@field public obj_10011 UnityEngine.GameObject
---@field public obj_10012 UnityEngine.GameObject
---@field public obj_10013 UnityEngine.GameObject
---@field public obj_10014 UnityEngine.GameObject
---@field public obj_10015 UnityEngine.GameObject
---@field public obj_avatar UnityEngine.GameObject
---@field public obj_coin UnityEngine.GameObject
---@field public obj_FurnitureFlyViewItem UnityEngine.GameObject
---@field public obj_Root UnityEngine.GameObject
---@field public obj_scene UnityEngine.GameObject
---@field public obj_shuxing UnityEngine.GameObject
---@field public obj_touch UnityEngine.GameObject
---@field public obj_transLayer UnityEngine.GameObject
---@field public obj_transport UnityEngine.GameObject
---@field public simg_10001 SEngine.UI.SImage
---@field public simg_10002 SEngine.UI.SImage
---@field public simg_10003 SEngine.UI.SImage
---@field public simg_10004 SEngine.UI.SImage
---@field public simg_10005 SEngine.UI.SImage
---@field public simg_10006 SEngine.UI.SImage
---@field public simg_10007 SEngine.UI.SImage
---@field public simg_10008 SEngine.UI.SImage
---@field public simg_10009 SEngine.UI.SImage
---@field public simg_10010 SEngine.UI.SImage
---@field public simg_10011 SEngine.UI.SImage
---@field public simg_10012 SEngine.UI.SImage
---@field public simg_10013 SEngine.UI.SImage
---@field public simg_10014 SEngine.UI.SImage
---@field public simg_10015 SEngine.UI.SImage

---@class LoungeSceneView_avatar_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public obj_avatar UnityEngine.GameObject
---@field public obj_avatarSkel UnityEngine.GameObject
---@field public obj_avatarSkel2 UnityEngine.GameObject
---@field public obj_content UnityEngine.GameObject
---@field public obj_dialog UnityEngine.GameObject
---@field public obj_Image UnityEngine.GameObject
---@field public sbtn_need SEngine.UI.SButton
---@field public simg_angry SEngine.UI.SImage
---@field public simg_need SEngine.UI.SImage
---@field public stmp_text SEngine.UI.STMP

---@class LoungeSceneView_coin_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public btn_anyClick UnityEngine.UI.Button
---@field public obj_finger UnityEngine.GameObject
---@field public obj_imgNodes UnityEngine.GameObject
---@field public obj_move UnityEngine.GameObject
---@field public obj_showCoins UnityEngine.GameObject
---@field public simg_image SEngine.UI.SImage

---@class LoungeSceneView_FurnitureFlyViewItem_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public img_icon SEngine.UI.SImage
---@field public stmp_coinStr SEngine.UI.STMP

---@class LoungeSceneView_transport_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public obj_effect UnityEngine.GameObject
---@field public obj_spine UnityEngine.GameObject
---@field public sbtn_unlock SEngine.UI.SButton
---@field public simg_unlock SEngine.UI.SImage

