---@class MainView_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public img_goldimg UnityEngine.UI.Image
---@field public img_image SEngine.UI.SImage
---@field public img_machinebar SEngine.UI.SImage
---@field public img_tabhotel SEngine.UI.SImage
---@field public img_tabItask SEngine.UI.SImage
---@field public img_tabshop SEngine.UI.SImage
---@field public img_tabstaff SEngine.UI.SImage
---@field public obj_bottom UnityEngine.GameObject
---@field public obj_coinMove UnityEngine.GameObject
---@field public obj_diamond UnityEngine.GameObject
---@field public obj_energy UnityEngine.GameObject
---@field public obj_fly UnityEngine.GameObject
---@field public obj_ghost UnityEngine.GameObject
---@field public obj_gold UnityEngine.GameObject
---@field public obj_goldFlyitem UnityEngine.GameObject
---@field public obj_HotelGrid UnityEngine.GameObject
---@field public obj_LoungeGrid UnityEngine.GameObject
---@field public obj_moveEnergyNode UnityEngine.GameObject
---@field public obj_moveNode UnityEngine.GameObject
---@field public obj_popular UnityEngine.GameObject
---@field public obj_PublicBot UnityEngine.GameObject
---@field public obj_right UnityEngine.GameObject
---@field public obj_timemessage UnityEngine.GameObject
---@field public obj_topleft UnityEngine.GameObject
---@field public sbtn_addenergy SEngine.UI.SButton
---@field public sbtn_anyClick SEngine.UI.SButton
---@field public sbtn_atlas SEngine.UI.SButton
---@field public sbtn_back SEngine.UI.SButton
---@field public sbtn_bag SEngine.UI.SButton
---@field public sbtn_device SEngine.UI.SButton
---@field public sbtn_friendly SEngine.UI.SButton
---@field public sbtn_hotel SEngine.UI.SButton
---@field public sbtn_machineknob SEngine.UI.SButton
---@field public sbtn_rank SEngine.UI.SButton
---@field public sbtn_setting SEngine.UI.SButton
---@field public sbtn_shop SEngine.UI.SButton
---@field public sbtn_showenergyMessage SEngine.UI.SButton
---@field public sbtn_staff SEngine.UI.SButton
---@field public sbtn_task SEngine.UI.SButton
---@field public simg_task SEngine.UI.SImage
---@field public stmp_allEnergy SEngine.UI.STMP
---@field public stmp_coinStr SEngine.UI.STMP
---@field public stmp_coinStr SEngine.UI.STMP
---@field public stmp_coinStr SEngine.UI.STMP
---@field public stmp_diamond SEngine.UI.STMP
---@field public stmp_energy SEngine.UI.STMP
---@field public stmp_ghost SEngine.UI.STMP
---@field public stmp_gold SEngine.UI.STMP
---@field public stmp_nextenergy SEngine.UI.STMP
---@field public stmp_popular SEngine.UI.STMP

---@class MainView_HotelGrid_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject

---@class MainView_LoungeGrid_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject

