---@class OfflineIncomView_GoTable
---@field public transform UnityEngine.Transform
---@field public gameObject UnityEngine.GameObject
---@field public btn_anyClose UnityEngine.UI.Button
---@field public sbtn_cancle SEngine.UI.SButton
---@field public sbtn_confirm SEngine.UI.SButton
---@field public simg_barimg SEngine.UI.SImage
---@field public stmp_iconNumstr SEngine.UI.STMP
---@field public stmp_iconNumstr2 SEngine.UI.STMP
---@field public stmp_LockStr SEngine.UI.STMP
---@field public stmp_offlineMaxTime SEngine.UI.STMP
---@field public stmp_offlinetimestr SEngine.UI.STMP
---@field public stmp_showTime SEngine.UI.STMP
---@field public stmp_specialNumStr SEngine.UI.STMP
---@field public stmp_title SEngine.UI.STMP
---@field public stmp_titleStr SEngine.UI.STMP
---@field public stmp_unlockStr SEngine.UI.STMP

