---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/10/8 17:16
---

local UIBase = require("UIBase")
local GameEvent = require("GameEvent")
local Log = require("Log")
local UIManager = require("UIManager")
local UIDefine = require("UIDefine")
local SceneInst = require("SceneManager"):GetInstance()

---@class LoginView : UIBase 窗口
---@field private go_table LoginView_GoTable GoTable
---@field private ParentCls UIBase 父窗口类
local LoginView = Class("LoginView", UIBase)
local Language = Language
local LanguageUtil = LanguageUtil

---添加Events监听事件
function LoginView:Awake()

    self:AddEvent(GameEvent.TestEvent1)
end
--- 窗口显示[protected]
---@param ... any @窗口传参
function LoginView:OnCreate()
    --local txt = Config.Language.Common_Sure.CN

    --local unlockTest = LanguageUtil:GetValue(Language.test,LanguageUtil:GetValue(Language.test2))
    self.go_table.sbtn_login:SetText(LanguageUtil:GetValue("Common_Login"))
end

---事件处理
---@private
---@param id EventID 事件ID
function LoginView:EventHandle(id, args)
    if id == GameEvent.TestEvent1 then
        self:OnTestEvent(args)
    end
end

function LoginView:OnTestEvent(args)
    local arg = args[1]
    Log.Debug("test args:", arg)
end

---点击Button回调
---@param btn UnityEngine.UI.Button 按钮
function LoginView:OnClickBtn(btn)
    if btn == self.go_table.sbtn_login then
        self:Login()
    end
end

function LoginView:Login()
    self:Close()
    Log.Debug("login start!!!!!")
    SceneInst:EnterHotel(true)
end

---数据清理
---@protected
function LoginView:OnDestroy()
    --LoginView.ParentCls.OnDestroy(self)
end

return LoginView