---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/10/8 17:16
---

local UIBase = require("UIBase")
local GameEvent = require("GameEvent")
local Log = require("Log")
local UIManager = require("UIManager")
local UIDefine = require("UIDefine")
local SceneInst = require("SceneManager"):GetInstance()
local LoginNet = require("LoginNet")
local NetManager = require("NetManager")
local GameData = require("GameData")
local PopManager = require("PopManager")
local UILayerEnum = UILayerEnum
local AppSetting = AppSetting

---@class LoginView : UIBase 窗口
---@field private go_table LoginView_GoTable GoTable
---@field private ParentCls UIBase 父窗口类
local LoginView = Class("LoginView", UIBase)
local Language = Language
local LanguageUtil = LanguageUtil

---添加Events监听事件
function LoginView:Awake()

    self:AddEvent(GameEvent.TestEvent1)
    self:AddEvent(GameEvent.ServerConnected)
    self:AddEvent(GameEvent.HttpResponseError)
end
--- 窗口显示[protected]
---@param ... any @窗口传参
function LoginView:OnCreate()
    --local txt = Config.Language.Common_Sure.CN

    --local unlockTest = LanguageUtil:GetValue(Language.test,LanguageUtil:GetValue(Language.test2))
    self.go_table.sbtn_login:SetText(LanguageUtil:GetValue("Common_Login"))
end

---事件处理
---@private
---@param id EventID 事件ID
function LoginView:EventHandle(id, args)
    if id == GameEvent.TestEvent1 then
        self:OnTestEvent(args)
    elseif id == GameEvent.ServerConnected then
        self:OnServerConnected(args)
    elseif id == GameEvent.HttpResponseError then
        self:OnHttpResponseError(args)
    end
end

function LoginView:OnTestEvent(args)
    local arg = args[1]
    Log.Debug("test args:", arg)
end

---点击Button回调
---@param btn UnityEngine.UI.Button 按钮
function LoginView:OnClickBtn(btn)
    if btn == self.go_table.sbtn_login then
        self.go_table.sbtn_login.gameObject:SetActive(false)
        self:Login()
    end
end

function LoginView:Login()
    Log.Debug("login start!!!!!")
    if AppSetting.RunOffline then
        self:Close()
        SceneInst:EnterHotel(true)
    else
        local account = GameData:GetInstance().AccountData.Account
        local password = GameData:GetInstance().AccountData.Password
        NetManager:GetInstance():ConnectServer(account,password)
    end
end

function LoginView:OnHttpResponseError(msg)
    PopManager:GetInstance():ShowCommonTips(msg)
    self.go_table.sbtn_login.gameObject:SetActive(true)
end

function LoginView:OnServerConnected()
    Log.Info("Server Connected!!")
    LoginNet:GetInstance():Login(function()
        self:Close()
        SceneInst:EnterHotel(true)

    end)
end

---数据清理
---@protected
function LoginView:OnDestroy()
    --LoginView.ParentCls.OnDestroy(self)
end

return LoginView