---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/12/29 18:22
---
local NetManager = require("NetManager")
local ProtocolEnum = require("ProtocolEnum")
local GameData = require("GameData")

---@class LoginNet : Singleton 登录接口
local LoginNet = Class("LoginNet", Singleton)

function LoginNet:__init()
    ---注册回调
    NetManager:GetInstance():RegisterMsg(ProtocolEnum.LOGIN_RSP,self.LoginOK,self.LoginError)
end

--region -------------登录-------------
---登录请求
function LoginNet:Login(okCb,errorCb)
    ---@type LoginInfo
    local loginInfo = {
        UserID = GameData:GetInstance().AccountData.UserId,
        Account = GameData:GetInstance().AccountData.Account,
        Token = GameData:GetInstance().AccountData.Token,
    }
    NetManager:GetInstance():SendMsg(ProtocolEnum.LOGIN_REQ,loginInfo,ProtocolEnum.LOGIN_RSP,okCb,errorCb)
    --CS.Game.Network.NetworkKit:TestMessage()
end

---@param ackParam UserInfo
---@param reqParam LoginInfo
function LoginNet:LoginOK(ackParam,reqParam)

end
---@param ackParam UserInfo
---@param reqParam LoginInfo
function LoginNet:LoginError(ackParam,reqParam)

end

--endregion -------------登录-------------

return LoginNet
