---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/10/18 18:36
---
---@class LoopListViewHelper
local LoopListViewHelper = {}

---初始化普通列表
---@public
---@param target UIBase|UIComBase 绑定的target
---@param listView SuperScrollView.LoopListView2 列表对象
---@param listData any[] 列表数据
---@param itemComPrefab string 列表项预制体名字
---@param ... any 列表项目的参数
function LoopListViewHelper.InitCommonListView(target,listView,listData,itemComPrefab,...)
    local params = table.pack(...)
    local listViewGetItem = function(_,_,index)
        index = index + 1
        if index <0 or index > #listData then
            return nil
        end
        local listViewItem = listView:NewListViewItem(itemComPrefab)
        ---@type ListItemBase
        local itemCom = target:GetOrAddComponent(listViewItem.gameObject,require(itemComPrefab))
        itemCom:_InitItemData(listData[index],index,listData,table.unpack(params))
        return listViewItem
    end
    listView:InitListView(#listData,handler(target,listViewGetItem))
end

---设置嵌套的外层列表可滚动
---@param listView SuperScrollView.LoopListView2 滚动loopList
---@param parentListView SuperScrollView.LoopListView2 外层滚动loopList
function LoopListViewHelper.SetParentListDragEnable(listView,parentListView)
    local scrollRect = listView:GetComponent(typeof(CS.SEngine.UI.SScrollRect))
    if not IsNil(scrollRect) then
        local parentScrollRect = parentListView:GetComponent(typeof(CS.SEngine.UI.SScrollRect))
        if IsNil(parentScrollRect) then
            parentScrollRect = parentListView:GetComponent(typeof(CS.UnityEngine.UI.ScrollRect))
            if not IsNil(parentScrollRect) then
                scrollRect.ParentScrollRect = parentScrollRect
            end
        end
    end
end

_G.LoopListViewHelper = LoopListViewHelper
return LoopListViewHelper