---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/12/6 15:14
---
local UIComBase = require("UIComBase")
local EventManager = require("EventManager")
local GameEvent = require("GameEvent")
local HotelData = require("HotelData")
local MapManager = require("MapManager")
local DeviceData = require("DeviceData")
local GameData = require("GameData")

---@class CoinView : UIComBase 金币收取组件
---@field private go_table CoinView_GoTable GoTable
---@field private ParentCls UIBase 父窗口类
---@field Data HotelCoinData 金币数据
---@field FurnitureFieldId number 所属的家具类型id
---@field DropIndex number 掉落位置index
local CoinView = Class("CoinView", UIComBase)

---添加Events监听事件
function CoinView:Awake()
end
--- 窗口显示[protected]
---@param coinData HotelCoinData @窗口传参
function CoinView:OnCreate(coinData)
    self.Data = coinData
    self.FurnitureFieldId = coinData.FurnitureFieldId
    self.DropIndex = coinData.DropIndex
    self.RoomId = coinData.RoomId
    self.DropCount = coinData.DropCount
    self.Incom = coinData.InCome

    self.PropType = coinData.PropType --收益类型

    self.go_table.btn_anyClick.gameObject:SetActive(true)
    self.go_table.obj_move.gameObject:SetActive(false)
    self.go_table.obj_imgNodes:SetActive(false)

    self.OffSet = 20
    self.MaxNum = 15
    --[[    local inCom = DeviceData:GetInstance():FurnitureRoomIncom(self.RoomId, self.FurnitureFieldId, self.PropType)
        local inComCount = inCom * self.DropCount
        print("金币数量:" .. inComCount)]]
end
function CoinView:initCoin()


    local count = self.DropCount
    if (count > self.MaxNum) then
        count = self.MaxNum
    end
    for i = 1, count do
        local endPos = Vector3.New(0, 0, 0)
        endPos = Vector3.New(endPos.x + Mathf.Random(-self.OffSet, self.OffSet), endPos.y + Mathf.Random(-self.OffSet, self.OffSet), 0)
        ---@type UnityEngine.GameObject
        local coinGo = CS.UnityEngine.Object.Instantiate(self.go_table.obj_imgNodes, self.go_table.obj_showCoins.transform)
        coinGo.transform.localPosition = endPos
        coinGo.transform.gameObject:SetActive(true)

        local seq = CS.DG.Tweening.DOTween.Sequence()
        seq:Append(coinGo.transform:DOLocalMove(Vector3.New(coinGo.transform.localPosition.x, coinGo.transform.localPosition.y + 1, 0), 1))
        seq:Append(coinGo.transform:DOLocalMove(Vector3.New(coinGo.transform.localPosition.x, coinGo.transform.localPosition.y, 0), 1))

        local num = Mathf.Random(1, self.DropCount)
        if (num % 2 == 0) then
            seq:AppendInterval(0.5)
        end

        seq:SetLoops(-1)
    end
end
---播放金币掉落
function CoinView:ShowCoinEffect()
    self.go_table.btn_anyClick.gameObject:SetActive(false)

    local endPos = MapManager:GetInstance():GetFurnitureCoinPos(self.RoomId, self.FurnitureFieldId, self.DropIndex)


    --self.go_table.obj_imgNodes:SetActive(false)
    local startPos = MapManager:GetInstance():GetFurnitureUsePos(self.RoomId, self.FurnitureFieldId, self.DropIndex)

    local movePos = startPos - endPos

    --Log.Info("掉落次数：%s", self.Data.DropCount)

    --local inCom = DeviceData:GetInstance():FurnitureRoomIncom(self.RoomId, self.FurnitureFieldId, self.PropType)
    -- if (inCom <= 0) then
    --    return
    -- end

    --print("收益:" .. inCom)
    -- HotelData:GetInstance():UpdateCoinData(self.Data, inCom)

    self.go_table.obj_move.gameObject:SetActive(true)
    self.go_table.obj_move.transform.localPosition = movePos

    local targetPos = Vector3.New(0, 0, 0)
    targetPos = Vector3.New(targetPos.x + Mathf.Random(-self.OffSet, self.OffSet), targetPos.y + Mathf.Random(-self.OffSet, self.OffSet), 0)
    self.go_table.obj_move.transform:DOLocalMove(targetPos, 1):OnComplete(function()

        if (self.DropCount < self.MaxNum) then
            ---@type UnityEngine.GameObject
            local coinGo = CS.UnityEngine.Object.Instantiate(self.go_table.obj_imgNodes, self.go_table.obj_showCoins.transform)
            local pos = self.go_table.obj_move.transform:ConvertLocalPositionToParent(CSUIModel.UICamera, self.transform)
            coinGo.transform.localPosition = pos
            --.transform.gameObject:SetActive(false)
            coinGo.transform.gameObject:SetActive(true)

            local seq = CS.DG.Tweening.DOTween.Sequence()
            seq:Append(coinGo.transform:DOLocalMove(Vector3.New(coinGo.transform.localPosition.x, coinGo.transform.localPosition.y + 1, 0), 1))
            seq:Append(coinGo.transform:DOLocalMove(Vector3.New(coinGo.transform.localPosition.x, coinGo.transform.localPosition.y, 0), 1))
            local num = Mathf.Random(1, self.DropCount)
            if (num % 2 == 0) then
                seq:AppendInterval(0.5)
            end
            seq:SetLoops(-1)
        else

            for i = 1, self.go_table.obj_showCoins.transform.childCount do
                self.go_table.obj_showCoins.transform:GetChild(i - 1):GetChild(0):GetComponent(typeof(CS.UnityEngine.UI.Image)):ShowUIShiny(1.5)
            end
        end

        self.go_table.btn_anyClick.gameObject:SetActive(true)
        self.go_table.obj_move.gameObject:SetActive(false)
    end)
end

---事件处理
---@private
---@param id EventID 事件ID
function CoinView:EventHandle(id, args)
end

---可用
---@protected
function CoinView:OnEnable()
end

---不可用
---@protected
function CoinView:OnDisable()
end

---点击Button回调
---@param btn UnityEngine.UI.Button 按钮
function CoinView:OnClickBtn(btn)
    if btn == self.go_table.btn_anyClick then
        ---处理相关的收益

        local inCom = DeviceData:GetInstance():FurnitureRoomIncom(self.RoomId, self.FurnitureFieldId, self.PropType)
        local inComCount = inCom * self.Data.DropCount

        print("点击收集" .. self.Data.DropCount)

        GameData:GetInstance():ChangePlayerProp(GameDefine.ePlayerProp.Gold, inComCount)
        GameData:GetInstance():StartFlyCoin(self.transform, self.Data.DropCount)
        --发送收取金币
        HotelData:GetInstance():CollectCoin(self.Data)
        EventManager:GetInstance():Broadcast(GameEvent.CoinCollected, self.Data)
    end
end

---点击Toggle回调
---@protected
---@param toggle UnityEngine.UI.Toggle Toggle
---@param isOn boolean 是否选中
function CoinView:OnClickToggle(toggle, isOn)
end

---数据清理
---@protected
function CoinView:OnDestroy()
    --TemplateView.ParentCls.OnDestroy(self)
    self.gameObject:DestroyGameObj()
end

return CoinView