---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/9/30 15:37
---
---@class UILayerEnum @UI层级枚举
---@field SceneLayer number @场景层Layer(e.g. 场景等所在层)
---@field WindowLayer number @窗口层(所有普通窗口都在这一层)
---@field InfoLayer number @提示层()
---@field TopLayer number @顶层(e.g. 引导等所在层)
local UILayerEnum = {
    SceneLayer = 0,
    WindowLayer = 1,
    InfoLayer = 2,
    TopLayer = 9,
}
---@type UILayerEnum @UI层级枚举(枚举值有用到，必须为int且从0开始，请勿轻易修改)
_G.UILayerEnum = UILayerEnum

---@return UILayerEnum @UI层级枚举
return UILayerEnum