---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/11/29 12:48
local UIBase = require("UIBase")
local MapManager = require("MapManager")

---@class MapView : UIBase 窗口
---@field private go_table MapView_GoTable GoTable
---@field private ParentCls UIBase 父窗口类
local MapView = Class("MapView", UIBase)

---添加Events监听事件
function MapView:Awake()

end

--- 窗口显示[protected]
---@param ... any @窗口传参
function MapView:OnCreate()
    --初始化地图信息
    self:InitMap()
end

function MapView:InitMap()
    --if AppSetting.TileMapEnable then
        ---@type SEngine.Map.InitMap
        local InitMapComp = self.gameObject:GetComponent(typeof(CS.SEngine.Map.InitMap))
        if InitMapComp ~= nil then
            InitMapComp:Init(function()
                MapManager:GetInstance():InitAllMap()
            end)
        end
    --end
end

---数据清理
---@protected
function MapView:OnDestroy()
end
return MapView