---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Simon.L.
--- DateTime: 2022/9/29 15:25
---

---@class GameDefine
local GameDefine = {}
_G.GameDefine = GameDefine


--region -------------网络-------------

---@class GlobalDefine.eConnectType 连接类型
GameDefine.eConnectType = {
    ---游戏主连接
    Game = 1,
    ---聊天连接
    Chat = 2,
}

--endregion

--region -------------资源路径-------------

---@class GlobalDefine.eResPath 资源路径
GameDefine.eResPath = {
    ---公共图集
    AtlasCommon = "AtlasSprites/Common/",
    ---main 图集
    AtlasMain = "AtlasSprites/Main/",
}
--endregion
return GameDefine