---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asd.
--- DateTime: 2022/10/9 19:02
---

local UIBase = require("UIBase")
local GameEvent = require("GameEvent")
local Log = require("Log")

---@class TemplateView : UIBase 窗口
---@field private go_table TemplateView_GoTable GoTable
---@field private ParentCls UIBase 父窗口类
local TemplateView = Class("TemplateView", UIBase)

---添加Events监听事件
function TemplateView:Awake()

end
--- 窗口显示[protected]
---@param ... any @窗口传参
function TemplateView:OnCreate()

end

---事件处理
---@private
---@param id EventID 事件ID
function TemplateView:EventHandle(id, args)
end

---可用
---@protected
function TemplateView:OnEnable()
end

---不可用
---@protected
function TemplateView:OnDisable()
end

---点击Button回调
---@param btn UnityEngine.UI.Button 按钮
function TemplateView:OnClickBtn(btn)
end

---点击Toggle回调
---@protected
---@param toggle UnityEngine.UI.Toggle Toggle
---@param isOn boolean 是否选中
function TemplateView:OnClickToggle(toggle, isOn)
end

---数据清理
---@protected
function TemplateView:OnDestroy()
    --TemplateView.ParentCls.OnDestroy(self)
end

return TemplateView